### ISSUE TITLE
Metamask error from not using async calls

### ISSUE THREAD

**Issue by eshohet** [noman-land/dMail#4]
Error: The MetaMask Web3 object does not support synchronous methods like eth_call without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.

To reproduce:

Load webpage using browser that has metamask installed.

**Comment by noman-land** [comment]
Thank you, working on that in #5. If you use a local geth node it should get around the problem for now.
